[conf]
;port=/dev/ttyESP-58:8C:81:AA:17:80
;port=/dev/ttyESP-50:78:7D:91:F2:1C
;port=/dev/ttyESP-58:8C:81:AA:02:94

;90
;port=/dev/ttyESP-50:78:7D:8F:E3:44

;91
port=/dev/ttyESP-58:8C:81:AD:2D:68

;92
;port=/dev/ttyESP-50:78:7D:91:F1:F0

[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1

framework = arduino
build_unflags = -std=gnu++11  # remove the default
build_flags = 
  -DARDUINO_USB_MODE=1 
  -DARDUINO_USB_CDC_ON_BOOT=1 
  -DDEVICE_ID=91
  -std=c++17
  -Ilib

lib_extra_dirs=../device-lib
monitor_speed = 115200

upload_port=${conf.port}
monitor_port=${conf.port}
